import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { AuditResult } from "../../../lib/engine/types";

// Initialize the Google Generative AI client if the API key exists
const geminiApiKey = process.env.GEMINI_API_KEY;
const genAI = geminiApiKey ? new GoogleGenerativeAI(geminiApiKey) : null;

export async function POST(req: NextRequest) {
  try {
    const auditResult = (await req.json()) as AuditResult;
    if (!auditResult) {
      return NextResponse.json({ error: "Missing audit result data." }, { status: 400 });
    }

    if (!genAI || !geminiApiKey) {
      // Graceful fallback when Gemini API key is not configured
      const fallback = generateFallbackSummary(auditResult);
      return NextResponse.json({ summary: fallback, mode: "fallback" });
    }

    const { teamSize, useCase } = auditResult.input;
    const { totalCurrentSpend, totalMonthlySavings, totalAnnualSavings } = auditResult;

    const recommendationsText = auditResult.recommendations
      .map(
        (r) =>
          `- ${r.toolName}: Active Plan: ${r.currentPlanName} -> Suggested Plan: ${r.recommendedPlanName}. Action: ${r.action}. Savings: $${r.monthlySavings}/mo. Reason: ${r.reason}`
      )
      .join("\n");

    const prompt = `You are a startup CFO and AI engineering operations expert advising a founder of a ${teamSize}-person team who primarily uses their stack for "${useCase}".
Here is their audited monthly AI spend data:
- Total Current Monthly Spend: $${totalCurrentSpend}
- Potential Monthly Savings Identified: $${totalMonthlySavings}
- Potential Annual Savings: $${totalAnnualSavings}

Here are the specific recommendations generated by our rules engine:
${recommendationsText}

Task: Write a concise, professional, and actionable executive summary paragraph of about 80-120 words.
Focus on explaining where their biggest savings leverage is (e.g. redundant IDE licenses, seat counts, API prompt caching, or credit swapping) and why consolidating makes sense. Make the advice sound direct, analytical, and tailored to their team size. Avoid generic fluff. Do not mention "as an AI" or "based on the rules". Start directly with the core analysis.`;

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const response = await model.generateContent(prompt);
    const generatedText = response.response.text();

    const summaryText = generatedText ? generatedText.trim() : generateFallbackSummary(auditResult);
    return NextResponse.json({ summary: summaryText, mode: "gemini" });

  } catch (error) {
    console.error("Gemini API call failed, using fallback summary:", error);
    const fallback = generateFallbackSummary(auditResult);
    return NextResponse.json({ summary: fallback, mode: "fallback-error" });
  }
}

function generateFallbackSummary(audit: AuditResult): string {
  const { teamSize, useCase } = audit.input;
  const { totalMonthlySavings, totalCurrentSpend, recommendations } = audit;
  
  if (totalMonthlySavings === 0) {
    return `Your team of ${teamSize} has a lean, optimal AI stack tuned for ${useCase} operations. There is no active subscription leakage or seat count redundancy detected in your setup. Continue maintaining this configuration to prevent software cost inflation.`;
  }

  const primaryLeak = recommendations.find(r => r.monthlySavings > 0);
  const leakReason = primaryLeak 
    ? `Optimizing your ${primaryLeak.toolName} licenses ($${primaryLeak.monthlySavings}/mo savings)`
    : "consolidating overlapping subscription accounts";

  return `Your stack shows an optimization opportunity of $${totalMonthlySavings}/mo (representing a ${Math.round((totalMonthlySavings / totalCurrentSpend) * 100)}% spend reduction). The primary leverage comes from ${leakReason}. Consolidating redundant subscriptions and adjusting seats to your active team size of ${teamSize} will immediately reclaim cash flow without slowing down your product development velocity.`;
}
